# Generated by Django 4.2 on 2024-03-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='package_image',
        ),
    ]
